/**
 * Bundles packages/local-db/migrations/*.sql into a typed TS module so the
 * device worker can apply them WITHOUT fetch/file access. Regenerate after
 * every `pnpm --filter @chorify/local-db generate`:
 *
 *   npx tsx packages/local-db/scripts/bundle-migrations.ts
 *
 * Output is a GENERATED ARTIFACT — commit separately from hand edits.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const folder = new URL('../migrations', import.meta.url).pathname;
const journal = JSON.parse(readFileSync(join(folder, 'meta', '_journal.json'), 'utf8')) as {
  entries: Array<{ idx: number; when: number; tag: string }>;
};

const entries = journal.entries.map((entry) => {
  const sql = readFileSync(join(folder, `${entry.tag}.sql`), 'utf8');
  return { tag: entry.tag, sql };
});

const out = `/* eslint-disable */
// GENERATED by scripts/bundle-migrations.ts — do not edit by hand.
// Source of truth: packages/local-db/migrations (drizzle-kit sqlite track).

export interface DeviceMigration {
  readonly tag: string;
  readonly sql: string;
}

export const DEVICE_MIGRATIONS: readonly DeviceMigration[] = ${JSON.stringify(entries, null, 2)};
`;

writeFileSync(new URL('../src/migrations.generated.ts', import.meta.url).pathname, out);
console.log(`bundled ${entries.length} migration(s)`);
